// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFH2gIPY6w_bo4IZ9seyEQKKGSHCYyxK8',
    appId: '1:931182726232:web:ad9080e0c43535e8164e2d',
    messagingSenderId: '931182726232',
    projectId: 'iotproject-9cf99',
    authDomain: 'iotproject-9cf99.firebaseapp.com',
    databaseURL: 'https://iotproject-9cf99-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-9cf99.appspot.com',
    measurementId: 'G-P45ZWYPXGV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnzxDBeDzFXWadHSU0pgWtRyvb54lIVNQ',
    appId: '1:931182726232:android:a593f946d8186141164e2d',
    messagingSenderId: '931182726232',
    projectId: 'iotproject-9cf99',
    databaseURL: 'https://iotproject-9cf99-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-9cf99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVpmZToTzegRCUkeyRQauSkNR1s9yyEks',
    appId: '1:931182726232:ios:dd14361578f8f1f7164e2d',
    messagingSenderId: '931182726232',
    projectId: 'iotproject-9cf99',
    databaseURL: 'https://iotproject-9cf99-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-9cf99.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVpmZToTzegRCUkeyRQauSkNR1s9yyEks',
    appId: '1:931182726232:ios:dd14361578f8f1f7164e2d',
    messagingSenderId: '931182726232',
    projectId: 'iotproject-9cf99',
    databaseURL: 'https://iotproject-9cf99-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-9cf99.appspot.com',
    iosBundleId: 'com.example.smarthome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFH2gIPY6w_bo4IZ9seyEQKKGSHCYyxK8',
    appId: '1:931182726232:web:83761975599e9b24164e2d',
    messagingSenderId: '931182726232',
    projectId: 'iotproject-9cf99',
    authDomain: 'iotproject-9cf99.firebaseapp.com',
    databaseURL: 'https://iotproject-9cf99-default-rtdb.firebaseio.com',
    storageBucket: 'iotproject-9cf99.appspot.com',
    measurementId: 'G-HJH5L4YSSM',
  );

}